# Dockerfile for Telemetry Data Generator
FROM python:3.9-slim

WORKDIR /app

# Copy requirements file
COPY requirements.txt /app/

# Install dependencies
RUN pip install -r requirements.txt

# Copy the src directory
COPY src/app2 /app/

# Set the entry point
CMD ["python", "telemetry_generator.py"]