# Dockerfile for Flask Server
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy requirements file
COPY requirements.txt /app/

# Install dependencies
RUN pip install -r requirements.txt

# Copy the src directory
COPY src/app1 /app/

# expose the port
EXPOSE 5000

# Set the entry point
CMD ["python", "api_server.py"]